name: lint

on: [push, pull_request]

jobs:
  lint:
    # Run on a push to a branch within the repository.
    # Run on a PR from an external repository.
    # Skip on a PR from a branch within the repository.
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' &&
         github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-latest

    steps:
      - name: Clone the project
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8
        run: pip3 install flake8

      - name: Run flake8
        run: flake8 *.py
